version: '3.4'

services:
  restoranuvaldymosistema:
    image: restoranuvaldymosistema:dev
    container_name: RestoranuValdymoSistema
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "RestoranuValdymoSistema"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_restoranuvaldymosistema$
    volumes:
      - C:\Users\Arunas\source\repos\RestoranuValdymoSistema\RestoranuValdymoSistema\RestoranuValdymoSistema:/app
      - C:\Users\Arunas\source\repos\RestoranuValdymoSistema\RestoranuValdymoSistema:/src
      - C:\Users\Arunas\vsdbg\vs2017u5:/remote_debugger:rw
#$nuget_volume_mapping_restoranuvaldymosistema$
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_restoranuvaldymosistema$ \"/app/bin/Debug/net6.0/RestoranuValdymoSistema.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true